Homework4
Sophiabattler/homework-repository pull request #4
Opened 2021-05-18 19:13 UTC by Sophiabattler

@Chanterz сделала четвертую, но не уверенна в первом тесте второго задания

2021-05-24 08:40 UTC, Chanterz requested changes
Доработать тесты для второй таски

2021-05-24 08:40 UTC, Chanterz commented on homework4/task01.py
> +        raise ValueError from None
А с какой целью `from None`?

2021-05-24 08:40 UTC, Chanterz commented on tests/homework4/test_task01.py
> +        pass
```suggestion

```

2021-05-24 08:40 UTC, Chanterz commented on tests/homework4/test_task02.py
> +        self.assertEqual(count_dots_on_i(url), 10)
Ты здесь свой мок проверяешь? :)

2021-05-25 10:03 UTC, Sophiabattler commented on homework4/task01.py
> +        raise ValueError from None
https://docs.python.org/3/library/exceptions.html#built-in-exceptions

2021-05-28 10:51 UTC, Sophiabattler commented
Исправила тесты для 2 задания

2021-06-01 11:36 UTC, merged