Homework6
Sophiabattler/homework-repository pull request #6
Opened 2021-05-30 18:15 UTC by Sophiabattler

2021-05-30 18:22 UTC, Sophiabattler commented
был конфликт между проверками блэк и исорт, и я добавила флажок исорту, чтобы они не конфликтовали

2021-06-01 10:33 UTC, Chanterz requested changes

2021-06-01 10:33 UTC, Chanterz commented on homework6/task01.py
> +        if "count_inst" not in cls.__dict__:
лучше это делать через `hasattr`

2021-06-01 10:33 UTC, Chanterz commented on homework6/task01.py
> +            self.__class__.count_inst += 1
Здесь к классу можно не обращаться

2021-06-01 10:33 UTC, Chanterz commented on homework6/task02.py
> +    """Parent class for initialization of Teacher and Student."""
У тебя ж ооп для того и есть, чтобы все универсилизовать и абстрагироваться, зачем писать, что этот класс только для тичера и стьюдента?)

2021-06-01 10:57 UTC, Sophiabattler commented on homework6/task01.py
> +            self.__class__.count_inst += 1
тесты не проходят, если не обращаться к классу(

2021-06-01 11:07 UTC, Sophiabattler commented on homework6/task02.py
> +    """Parent class for initialization of Teacher and Student."""
исправила на """Initializes name and lastname of Person"""

2021-06-01 11:08 UTC, Sophiabattler commented on homework6/task01.py
> +        if "count_inst" not in cls.__dict__:
исправила на 
if not hasattr(cls, "count_inst"):

2021-06-01 11:37 UTC, merged