homework7
Sophiabattler/homework-repository pull request #7
Opened 2021-06-01 16:49 UTC by Sophiabattler

2021-06-10 09:15 UTC, Chanterz requested changes

2021-06-10 09:15 UTC, Chanterz commented on homework7/task01.py
> +        if item == element and type(item) == type(element):
Ого, а в каких случаях проверки просто на равенство будет недостаточно?)

2021-06-10 09:15 UTC, Chanterz commented on homework7/task01.py
> +        elif type(item) == (bool or int):
Здесь нужно использовать `isinstance`. В данный момент этот код будет работать не так, как ты задумала

2021-06-10 09:15 UTC, Chanterz commented on homework7/task01.py
> +        elif type(item) != (str or bool or int) and item != element:
Ой, и здесь

2021-06-10 09:15 UTC, Chanterz commented on homework7/task02.py
> +        return new_word
Может есть идеи, как упростить, используя стек? https://ru.wikipedia.org/wiki/Стек Если что у списка все методы стека есть.

2021-06-10 20:12 UTC, Sophiabattler commented on homework7/task01.py
> +        if item == element and type(item) == type(element):
в случае True и 1

2021-06-10 22:43 UTC, Sophiabattler commented on homework7/task02.py
> +        return new_word
исправила

2021-06-11 00:20 UTC, Sophiabattler commented on homework7/task01.py
> +        elif type(item) == (bool or int):
исправила

2021-06-11 00:21 UTC, Sophiabattler commented on homework7/task01.py
> +        elif type(item) != (str or bool or int) and item != element:
и здесь тоже

2021-06-11 00:22 UTC, Sophiabattler commented on homework7/task01.py
> +        if item == element and type(item) == type(element):
если изменить type(item) == type(element) на item is element, тогда тесты некоторые слетают

2021-06-11 10:50 UTC, merged